project_id = "pbwknkonvukyukeipvzk"

[auth]
enabled = true
site_url = "https://id-preview--36606a72-6807-49ee-80d9-99f2c7655fc6.lovable.app"

[auth.email]
enable_confirmations = false
enable_signup = true
